import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

import os
from fpdf import FPDF

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sample-contracts")
os.makedirs(OUTPUT_DIR, exist_ok=True)


class ContractPDF(FPDF):
    def __init__(self, title="", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._doc_title = title
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.cell(0, 5, self._doc_title, align="C", ln=True)
            self.set_draw_color(180, 180, 180)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{{chr(110)}b}}", align="C", ln=True)
        self.cell(0, 4, "CONFIDENTIAL", align="C", ln=True)

    def title_page(self, doc_type, parties, date_line, reference=""):
        self.add_page()
        self.ln(50)
        self.set_font("Helvetica", "B", 26)
        self.cell(0, 14, doc_type, align="C", ln=True)
        self.ln(8)
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.8)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(12)
        self.set_font("Helvetica", "", 14)
        for p in parties:
            self.cell(0, 10, p, align="C", ln=True)
        self.ln(10)
        self.set_font("Helvetica", "I", 12)
        self.cell(0, 8, date_line, align="C", ln=True)
        if reference:
            self.ln(4)
            self.set_font("Helvetica", "", 11)
            self.cell(0, 8, reference, align="C", ln=True)

    def section_heading(self, number, title):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, f"{number}. {title}", ln=True)
        self.ln(1)

    def subsection_heading(self, number, title):
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 7, f"    {number} {title}", ln=True)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 5.5, text, ln=True)
        self.ln(1)

    def signature_block(self, parties):
        self.ln(8)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 7, "IN WITNESS WHEREOF, the Parties have executed this Agreement as of the date first written above.", ln=True)
        self.ln(10)
        col_w = 90
        y_start = self.get_y()
        for i, (name, title, company) in enumerate(parties):
            x = 10 + i * col_w
            self.set_xy(x, y_start)
            self.set_font("Helvetica", "B", 10)
            self.cell(col_w, 6, company, ln=True)
            self.set_x(x)
            self.ln(12)
            self.set_x(x)
            self.set_draw_color(0, 0, 0)
            self.line(x, self.get_y(), x + 75, self.get_y())
            self.ln(2)
            self.set_font("Helvetica", "", 9)
            self.set_x(x)
            self.cell(col_w, 5, f"Name: {name}", ln=True)
            self.set_x(x)
            self.cell(col_w, 5, f"Title: {title}", ln=True)
            self.set_x(x)
            self.cell(col_w, 5, "Date: _______________", ln=True)


def gen_nda():
    pdf = ContractPDF("Mutual Non-Disclosure Agreement - TechCorp / Nexus Dynamics")
    pdf.alias_nb_pages()
    pdf.title_page("MUTUAL NON-DISCLOSURE AGREEMENT", ["TechCorp Solutions, Inc.", "and", "Nexus Dynamics LLC"], "Effective Date: January 15, 2024")
    pdf.add_page()
    pdf.body_text('This Mutual Non-Disclosure Agreement ("Agreement") is entered into as of January 15, 2024 (the "Effective Date") by and between TechCorp Solutions, Inc., a Delaware corporation with its principal office at 1200 Innovation Drive, San Jose, CA 95134 ("TechCorp"), and Nexus Dynamics LLC, a California limited liability company with its principal office at 800 Market Street, Suite 400, San Francisco, CA 94102 ("Nexus Dynamics"). TechCorp and Nexus Dynamics are each referred to herein as a "Party" and collectively as the "Parties."')
    pdf.section_heading("1", "PURPOSE")
    pdf.body_text('The Parties wish to explore a potential business relationship concerning joint technology development and strategic partnership opportunities (the "Purpose"). In connection with the Purpose, each Party may disclose to the other certain confidential and proprietary information. The Parties desire to establish the terms under which such information will be disclosed and protected.')
    pdf.section_heading("2", "DEFINITION OF CONFIDENTIAL INFORMATION")
    pdf.body_text('"Confidential Information" means any and all non-public, proprietary, or confidential information disclosed by either Party (the "Disclosing Party") to the other Party (the "Receiving Party"), whether orally, in writing, electronically, or by inspection of tangible objects, including but not limited to: (a) trade secrets, inventions, ideas, processes, formulas, source and object code, data, programs, software, other works of authorship, know-how, improvements, discoveries, and developments; (b) information regarding plans for research, development, new products, marketing and selling, business plans, budgets and unpublished financial statements, licenses, prices and costs, margins, discounts, credit terms, pricing and billing policies, quoting procedures, methods of obtaining business, forecasts, future plans, and potential strategies; (c) information regarding customers, suppliers, joint venture partners, and potential customers; and (d) information regarding the skills and compensation of employees, contractors, or agents of the Disclosing Party.')
    pdf.section_heading("3", "OBLIGATIONS OF THE RECEIVING PARTY")
    pdf.subsection_heading("3.1", "Non-Disclosure")
    pdf.body_text("The Receiving Party shall not disclose any Confidential Information of the Disclosing Party to any third party without the prior written consent of the Disclosing Party, except to those employees, officers, directors, agents, consultants, and advisors of the Receiving Party who have a need to know such information for the Purpose and who are bound by obligations of confidentiality at least as protective as those contained herein.")
    pdf.subsection_heading("3.2", "Standard of Care")
    pdf.body_text("The Receiving Party shall protect the Disclosing Party's Confidential Information using the same degree of care that the Receiving Party uses to protect its own confidential information of a similar nature, but in no event less than reasonable care. The Receiving Party shall promptly notify the Disclosing Party in writing of any misuse, misappropriation, or unauthorized disclosure of Confidential Information of which the Receiving Party becomes aware.")
    pdf.subsection_heading("3.3", "Restricted Use")
    pdf.body_text("The Receiving Party shall use the Confidential Information solely for the Purpose and shall not use or exploit the Confidential Information for its own benefit or the benefit of any third party without the prior written consent of the Disclosing Party.")
    pdf.section_heading("4", "EXCLUSIONS FROM CONFIDENTIAL INFORMATION")
    pdf.body_text("Confidential Information shall not include information that: (a) is or becomes publicly available through no fault of the Receiving Party; (b) was known to the Receiving Party prior to disclosure by the Disclosing Party, as evidenced by written records; (c) is rightfully received by the Receiving Party from a third party without restriction on disclosure; or (d) is independently developed by the Receiving Party without use of or reference to the Disclosing Party's Confidential Information, as demonstrated by documented evidence.")
    pdf.section_heading("5", "TERM AND TERMINATION")
    pdf.body_text('This Agreement shall commence on the Effective Date and shall remain in effect for a period of three (3) years (the "Term"), unless earlier terminated by either Party upon thirty (30) days\' prior written notice to the other Party. The obligations of confidentiality set forth herein shall survive the expiration or termination of this Agreement for a period of three (3) years from the date of disclosure of the applicable Confidential Information.')
    pdf.section_heading("6", "RETURN OR DESTRUCTION OF MATERIALS")
    pdf.body_text("Upon termination or expiration of this Agreement, or upon the Disclosing Party's written request, the Receiving Party shall promptly return or destroy all tangible materials embodying Confidential Information, including all copies, notes, summaries, and extracts thereof. The Receiving Party shall certify in writing the completion of such return or destruction within fifteen (15) business days.")
    pdf.section_heading("7", "REMEDIES")
    pdf.body_text("Each Party acknowledges that any breach of this Agreement may cause irreparable harm to the Disclosing Party for which monetary damages may be inadequate. Accordingly, the Disclosing Party shall be entitled to seek equitable relief, including injunctive relief and specific performance, in addition to all other remedies available at law or in equity, without the need to post a bond.")
    pdf.section_heading("8", "GOVERNING LAW AND DISPUTE RESOLUTION")
    pdf.body_text("This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws principles. Any dispute arising out of or in connection with this Agreement shall be resolved through binding arbitration administered by the American Arbitration Association in San Jose, California, in accordance with its Commercial Arbitration Rules.")
    pdf.section_heading("9", "GENERAL PROVISIONS")
    pdf.body_text("This Agreement constitutes the entire agreement between the Parties with respect to the subject matter hereof and supersedes all prior and contemporaneous agreements, understandings, negotiations, and discussions. This Agreement may be amended only by a written instrument signed by both Parties. Neither Party may assign this Agreement without the prior written consent of the other Party. If any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.")
    pdf.signature_block([("James R. Whitfield", "Chief Executive Officer", "TechCorp Solutions, Inc."), ("Sarah M. Chen", "Managing Director", "Nexus Dynamics LLC")])
    pdf.output(os.path.join(OUTPUT_DIR, "Mutual-NDA-TechCorp-Nexus-2024.pdf"))


def gen_saas():
    pdf = ContractPDF("SaaS License Agreement - CloudVault Systems")
    pdf.alias_nb_pages()
    pdf.title_page("SAAS LICENSE AGREEMENT", ["GlobalTech Industries, Inc. (Customer)", "and", "CloudVault Systems, Inc. (Provider)"], "Effective Date: March 1, 2024", "Agreement No. CV-GLB-2024-0301")
    pdf.add_page()
    pdf.body_text('This SaaS License Agreement ("Agreement") is entered into as of March 1, 2024 (the "Effective Date") by and between CloudVault Systems, Inc., a Delaware corporation with its principal office at 500 Cloud Avenue, Suite 1200, Seattle, WA 98101 ("Provider"), and GlobalTech Industries, Inc., a Delaware corporation with its principal office at 2500 Corporate Boulevard, Chicago, IL 60601 ("Customer"). Provider and Customer are collectively referred to herein as the "Parties."')
    pdf.section_heading("1", "DEFINITIONS")
    pdf.body_text('"Services" means the CloudVault Enterprise Platform, including data management, analytics, and collaboration tools delivered as a cloud-based software-as-a-service solution, together with all updates, upgrades, and enhancements made generally available by Provider during the Term. "Documentation" means the user guides, online help, release notes, training materials, and other documentation provided by Provider to Customer regarding the use of the Services. "Authorized Users" means employees, contractors, and agents of Customer who are authorized by Customer to access and use the Services under this Agreement, up to the number specified in the applicable Order Form.')
    pdf.section_heading("2", "GRANT OF LICENSE AND ACCESS")
    pdf.subsection_heading("2.1", "License Grant")
    pdf.body_text("Subject to the terms and conditions of this Agreement, Provider hereby grants to Customer a non-exclusive, non-transferable, non-sublicensable right to access and use the Services during the Term solely for Customer's internal business purposes. The license includes up to five hundred (500) Authorized Users as specified in Order Form OF-2024-0301-A attached hereto.")
    pdf.subsection_heading("2.2", "Restrictions")
    pdf.body_text("Customer shall not: (a) sublicense, sell, resell, transfer, assign, distribute, or otherwise commercially exploit or make available to any third party the Services; (b) modify or make derivative works based upon the Services; (c) reverse engineer, disassemble, or decompile the Services or apply any other process to derive the source code; (d) access the Services in order to build a competitive product or service or copy any features, functions, or graphics of the Services.")
    pdf.section_heading("3", "FEES AND PAYMENT")
    pdf.subsection_heading("3.1", "Subscription Fees")
    pdf.body_text("Customer shall pay Provider an annual subscription fee of Four Hundred Eighty Thousand Dollars ($480,000.00) USD, payable in quarterly installments of One Hundred Twenty Thousand Dollars ($120,000.00) due on the first business day of each calendar quarter during the Term. The initial payment is due upon execution of this Agreement.")
    pdf.subsection_heading("3.2", "Fee Increases")
    pdf.body_text("Provider may increase the subscription fees for any Renewal Term by providing written notice to Customer at least ninety (90) days prior to the commencement of such Renewal Term. Fee increases shall not exceed five percent (5%) per annum.")
    pdf.subsection_heading("3.3", "Late Payments")
    pdf.body_text("Any amounts not paid when due shall bear interest at the lesser of one and one-half percent (1.5%) per month or the maximum rate permitted by applicable law. Customer shall reimburse Provider for all reasonable costs of collection, including attorneys\' fees.")
    pdf.section_heading("4", "SERVICE LEVEL AGREEMENT")
    pdf.subsection_heading("4.1", "Uptime Commitment")
    pdf.body_text('Provider guarantees a monthly uptime percentage of ninety-nine point nine percent (99.9%) for the Services, measured on a calendar month basis, excluding scheduled maintenance windows. "Uptime" means the total minutes in a calendar month minus the minutes of Downtime, divided by the total minutes in that calendar month. Scheduled maintenance will be performed during weekends (Saturday 12:00 AM to Sunday 6:00 AM Pacific Time) with at least 48 hours\' notice.')
    pdf.subsection_heading("4.2", "Service Credits")
    pdf.body_text("If Provider fails to meet the 99.9% uptime commitment, Customer shall be entitled to service credits as follows: (a) 99.0% to 99.9% uptime - 10% credit of monthly fees; (b) 95.0% to 98.9% uptime - 25% credit of monthly fees; (c) below 95.0% uptime - 50% credit of monthly fees. Service credits shall be applied against future invoices and shall not exceed 50% of the monthly subscription fee in any given month.")
    pdf.section_heading("5", "DATA SECURITY AND PRIVACY")
    pdf.body_text("Provider shall implement and maintain administrative, physical, and technical safeguards designed to protect Customer Data in accordance with industry standards, including SOC 2 Type II, ISO 27001, and applicable data protection laws including GDPR and CCPA. Provider shall encrypt all Customer Data in transit using TLS 1.2 or higher and at rest using AES-256 encryption. Provider shall notify Customer of any Security Breach within seventy-two (72) hours of discovery.")
    pdf.section_heading("6", "TERM AND TERMINATION")
    pdf.subsection_heading("6.1", "Initial Term")
    pdf.body_text('This Agreement shall commence on the Effective Date and shall continue for an initial term of three (3) years (the "Initial Term"), unless earlier terminated in accordance with this Section.')
    pdf.subsection_heading("6.2", "Renewal")
    pdf.body_text('Following the Initial Term, this Agreement shall automatically renew for successive one (1) year periods (each a "Renewal Term") unless either Party provides written notice of non-renewal at least ninety (90) days prior to the expiration of the then-current term.')
    pdf.subsection_heading("6.3", "Termination for Cause")
    pdf.body_text("Either Party may terminate this Agreement upon written notice if the other Party materially breaches this Agreement and fails to cure such breach within thirty (30) days after receiving written notice of the breach.")
    pdf.section_heading("7", "INTELLECTUAL PROPERTY")
    pdf.body_text("Provider retains all right, title, and interest in and to the Services, including all related intellectual property rights. Customer retains all right, title, and interest in and to Customer Data. No rights are granted to either Party except as expressly set forth herein.")
    pdf.section_heading("8", "LIMITATION OF LIABILITY")
    pdf.body_text("IN NO EVENT SHALL EITHER PARTY'S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE TOTAL AMOUNTS PAID BY CUSTOMER IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM. IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, REGARDLESS OF THE CAUSE OF ACTION OR THE THEORY OF LIABILITY.")
    pdf.section_heading("9", "GOVERNING LAW")
    pdf.body_text("This Agreement shall be governed by and construed in accordance with the laws of the State of Washington, without regard to its conflict of laws provisions. The Parties consent to the exclusive jurisdiction of the state and federal courts located in King County, Washington.")
    pdf.signature_block([("Michael D. Torres", "Chief Procurement Officer", "GlobalTech Industries, Inc."), ("Amanda L. Parker", "VP of Enterprise Sales", "CloudVault Systems, Inc.")])
    pdf.output(os.path.join(OUTPUT_DIR, "SaaS-License-CloudVault-2024.pdf"))


def gen_msa():
    pdf = ContractPDF("Master Service Agreement - Apple Inc. / Pinnacle Consulting")
    pdf.alias_nb_pages()
    pdf.title_page("MASTER SERVICE AGREEMENT", ["Apple Inc.", "and", "Pinnacle Consulting Group, Inc."], "Effective Date: July 1, 2023", "Agreement No. AAPL-PCG-MSA-2023-070")
    pdf.add_page()
    pdf.body_text('This Master Service Agreement ("Agreement") is entered into as of July 1, 2023 (the "Effective Date") by and between Apple Inc., a California corporation with its principal office at One Apple Park Way, Cupertino, CA 95014 ("Client"), and Pinnacle Consulting Group, Inc., a New York corporation with its principal office at 450 Park Avenue, 30th Floor, New York, NY 10022 ("Consultant"). Client and Consultant are collectively referred to as the "Parties."')
    pdf.section_heading("1", "SCOPE OF SERVICES")
    pdf.subsection_heading("1.1", "General")
    pdf.body_text('Consultant shall provide information technology consulting services, including but not limited to IT strategy, systems integration, data analytics, cloud migration, cybersecurity assessments, and digital transformation advisory services as described in individual Statements of Work (each, a "SOW") executed pursuant to this Agreement. Each SOW shall reference this Agreement and shall be subject to the terms and conditions herein.')
    pdf.subsection_heading("1.2", "Statements of Work")
    pdf.body_text("Each SOW shall specify: (a) a detailed description of the services to be performed; (b) the deliverables to be provided; (c) the project timeline and milestones; (d) the fees and payment schedule; (e) acceptance criteria for deliverables; (f) the personnel assigned to the project; and (g) any additional terms specific to the engagement.")
    pdf.section_heading("2", "COMPENSATION AND PAYMENT")
    pdf.subsection_heading("2.1", "Fee Structure")
    pdf.body_text("Fees for services shall be set forth in each SOW and may be structured as: (a) time-and-materials at the hourly rates specified in Exhibit A; (b) fixed-price for defined deliverables; or (c) a combination thereof. Standard hourly rates for the initial Term are as follows: Partner - $450/hour; Senior Consultant - $325/hour; Consultant - $250/hour; Analyst - $175/hour.")
    pdf.subsection_heading("2.2", "Invoicing")
    pdf.body_text("Consultant shall submit invoices monthly in arrears for time-and-materials engagements, or upon achievement of milestones for fixed-price engagements. Client shall pay all undisputed invoices within thirty (30) days of receipt. Client may dispute any invoice item in good faith by providing written notice within fifteen (15) days of receipt.")
    pdf.subsection_heading("2.3", "Expenses")
    pdf.body_text("Client shall reimburse Consultant for all reasonable and pre-approved out-of-pocket expenses incurred in connection with the performance of services, including travel, lodging, and meals, in accordance with Client's travel and expense policy. All expenses exceeding $5,000 in the aggregate per month require prior written approval from Client.")
    pdf.section_heading("3", "TERM AND TERMINATION")
    pdf.subsection_heading("3.1", "Term")
    pdf.body_text('This Agreement shall commence on the Effective Date and shall continue for an initial term of two (2) years (the "Initial Term"). Thereafter, this Agreement shall automatically renew for successive one (1) year periods (each a "Renewal Term") unless either Party provides written notice of non-renewal at least sixty (60) days prior to the expiration of the then-current term.')
    pdf.subsection_heading("3.2", "Termination for Convenience")
    pdf.body_text("Either Party may terminate this Agreement or any SOW for convenience upon sixty (60) days\' prior written notice to the other Party. In the event of such termination, Client shall pay Consultant for all services rendered and expenses incurred through the effective date of termination.")
    pdf.subsection_heading("3.3", "Termination for Cause")
    pdf.body_text("Either Party may terminate this Agreement or any SOW immediately upon written notice if the other Party: (a) materially breaches this Agreement and fails to cure such breach within thirty (30) days after written notice; (b) becomes insolvent, files for bankruptcy, or has a receiver appointed for a substantial part of its assets.")
    pdf.section_heading("4", "INTELLECTUAL PROPERTY")
    pdf.subsection_heading("4.1", "Work Product")
    pdf.body_text('All work product, deliverables, inventions, and materials created by Consultant in the performance of services under this Agreement ("Work Product") shall be the exclusive property of Client. Consultant hereby assigns to Client all right, title, and interest in and to the Work Product, including all intellectual property rights therein.')
    pdf.subsection_heading("4.2", "Pre-Existing IP")
    pdf.body_text("Consultant retains ownership of all pre-existing intellectual property, methodologies, tools, frameworks, and know-how owned or developed by Consultant prior to or independently of this Agreement. To the extent any pre-existing IP is incorporated into Work Product, Consultant grants Client a non-exclusive, royalty-free, perpetual, irrevocable license to use such pre-existing IP solely as part of the Work Product.")
    pdf.section_heading("5", "CONFIDENTIALITY")
    pdf.body_text("Each Party agrees to hold in confidence all Confidential Information received from the other Party and to use such information only for the purposes of this Agreement. The obligations of confidentiality shall survive the expiration or termination of this Agreement for a period of five (5) years.")
    pdf.section_heading("6", "REPRESENTATIONS AND WARRANTIES")
    pdf.body_text("Consultant represents and warrants that: (a) it has the expertise, qualifications, and resources to perform the services; (b) services will be performed in a professional and workmanlike manner in accordance with industry standards; (c) it will comply with all applicable laws and regulations; (d) the Work Product will not infringe upon any third-party intellectual property rights.")
    pdf.section_heading("7", "INDEMNIFICATION")
    pdf.body_text("Each Party shall indemnify, defend, and hold harmless the other Party from and against any and all third-party claims, damages, losses, costs, and expenses (including reasonable attorneys\' fees) arising out of or related to: (a) the indemnifying Party's breach of this Agreement; (b) the indemnifying Party's negligence or willful misconduct; or (c) any claim that the indemnifying Party's materials or deliverables infringe a third party's intellectual property rights.")
    pdf.section_heading("8", "LIMITATION OF LIABILITY")
    pdf.body_text("EXCEPT FOR OBLIGATIONS UNDER SECTIONS 5 AND 7, NEITHER PARTY'S AGGREGATE LIABILITY SHALL EXCEED THE TOTAL FEES PAID OR PAYABLE UNDER THE APPLICABLE SOW GIVING RISE TO THE CLAIM. NEITHER PARTY SHALL BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.")
    pdf.section_heading("9", "GOVERNING LAW")
    pdf.body_text("This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws provisions. Any dispute shall be resolved through binding arbitration in Santa Clara County, California, administered by JAMS under its Comprehensive Arbitration Rules.")
    pdf.signature_block([("Katherine A. Reynolds", "VP of Procurement", "Apple Inc."), ("Robert J. Manning", "Chief Executive Officer", "Pinnacle Consulting Group, Inc.")])
    pdf.output(os.path.join(OUTPUT_DIR, "MSA-Pinnacle-Consulting-2023.pdf"))


def gen_sow():
    pdf = ContractPDF("SOW #001 - Data Migration Project - Pinnacle Consulting")
    pdf.alias_nb_pages()
    pdf.title_page("STATEMENT OF WORK #001", ["Apple Inc.", "and", "Pinnacle Consulting Group, Inc."], "Effective Date: August 1, 2023", "Reference: MSA Agreement No. AAPL-PCG-MSA-2023-070")
    pdf.add_page()
    pdf.body_text('This Statement of Work #001 ("SOW") is entered into as of August 1, 2023, pursuant to and governed by the Master Service Agreement dated July 1, 2023 (the "MSA") between Apple Inc. ("Client") and Pinnacle Consulting Group, Inc. ("Consultant"). In the event of any conflict between this SOW and the MSA, the terms of this SOW shall control with respect to the services described herein.')
    pdf.section_heading("1", "PROJECT OVERVIEW")
    pdf.body_text('The purpose of this SOW is to define the scope, timeline, deliverables, and commercial terms for the Enterprise Data Migration Project (the "Project"). The Project involves the migration of Client\'s legacy on-premises data infrastructure, comprising approximately 50 terabytes of structured and unstructured data across 12 business-critical systems, to Client\'s designated cloud platform environment.')
    pdf.section_heading("2", "SCOPE OF WORK")
    pdf.subsection_heading("2.1", "Phase 1 - Discovery and Assessment (Weeks 1-4)")
    pdf.body_text("Consultant shall: (a) conduct a comprehensive inventory and assessment of existing data sources, schemas, and dependencies; (b) perform data quality analysis and profiling across all source systems; (c) identify and document data transformation requirements; (d) develop a detailed migration plan including risk mitigation strategies; (e) deliver a Discovery Report and Migration Architecture Document for Client review and approval.")
    pdf.subsection_heading("2.2", "Phase 2 - Design and Development (Weeks 5-12)")
    pdf.body_text("Consultant shall: (a) design the target data architecture and data models; (b) develop ETL/ELT pipelines for data extraction, transformation, and loading; (c) implement data validation and reconciliation frameworks; (d) configure the target cloud environment in accordance with Client's security and compliance requirements; (e) develop comprehensive test plans and test scripts.")
    pdf.subsection_heading("2.3", "Phase 3 - Testing and Validation (Weeks 13-18)")
    pdf.body_text("Consultant shall: (a) execute unit, integration, and system testing of all migration components; (b) perform parallel run testing comparing source and target data; (c) conduct user acceptance testing (UAT) with Client stakeholders; (d) remediate all identified defects; (e) obtain Client sign-off on test results prior to production migration.")
    pdf.subsection_heading("2.4", "Phase 4 - Production Migration and Cutover (Weeks 19-22)")
    pdf.body_text("Consultant shall: (a) execute the production data migration during agreed-upon maintenance windows; (b) perform post-migration data validation and integrity checks; (c) support Client's go/no-go decision process; (d) execute cutover to the new environment; (e) decommission legacy data systems upon Client approval.")
    pdf.subsection_heading("2.5", "Phase 5 - Hypercare and Knowledge Transfer (Weeks 23-26)")
    pdf.body_text("Consultant shall: (a) provide dedicated on-site and remote support during the hypercare period; (b) monitor system performance and data integrity; (c) resolve any post-migration issues; (d) deliver comprehensive knowledge transfer sessions and documentation to Client's IT team; (e) provide a final Project Closure Report.")
    pdf.section_heading("3", "DELIVERABLES")
    pdf.body_text("The following deliverables shall be provided under this SOW:\n  - Discovery Report and Data Inventory\n  - Migration Architecture Document\n  - ETL/ELT Pipeline Source Code and Configuration\n  - Data Validation and Reconciliation Reports\n  - Test Plans, Test Scripts, and Test Results\n  - UAT Sign-Off Documentation\n  - Post-Migration Validation Report\n  - Knowledge Transfer Materials and Runbooks\n  - Project Closure Report")
    pdf.section_heading("4", "PROJECT TIMELINE")
    pdf.body_text("The Project shall be completed within twenty-six (26) weeks from the SOW Effective Date, with a target completion date of January 31, 2024. Key milestones are as follows:\n  - Discovery Complete: August 28, 2023\n  - Design & Development Complete: October 23, 2023\n  - Testing & Validation Complete: December 8, 2023\n  - Production Migration Complete: January 12, 2024\n  - Project Closure: January 31, 2024")
    pdf.section_heading("5", "FEES AND PAYMENT SCHEDULE")
    pdf.subsection_heading("5.1", "Total Project Fee")
    pdf.body_text("The total fixed price for the Project is One Million Two Hundred Thousand Dollars ($1,200,000.00) USD. This fee is inclusive of all labor, materials, and Consultant expenses associated with the performance of the services described in this SOW.")
    pdf.subsection_heading("5.2", "Payment Milestones")
    pdf.body_text("Payment shall be made according to the following milestone schedule:\n  - SOW Execution (Deposit): $180,000 (15%)\n  - Discovery Phase Complete: $180,000 (15%)\n  - Design & Development Complete: $300,000 (25%)\n  - Testing & Validation Complete: $240,000 (20%)\n  - Production Migration Complete: $180,000 (15%)\n  - Project Closure & Final Acceptance: $120,000 (10%)")
    pdf.section_heading("6", "PROJECT TEAM")
    pdf.body_text("Consultant shall assign the following key personnel to the Project:\n  - Project Director: David Kim, Partner\n  - Lead Architect: Priya Sharma, Senior Consultant\n  - Data Engineer Lead: Marcus Johnson, Senior Consultant\n  - Testing Lead: Elena Vasquez, Consultant\n  - Project Manager: Thomas Wright, Consultant\n\nKey personnel may not be removed or reassigned without prior written consent of Client. Consultant shall maintain a minimum team size of eight (8) full-time equivalent resources throughout the Project duration.")
    pdf.section_heading("7", "CHANGE MANAGEMENT")
    pdf.body_text("Any change to the scope, schedule, or fees described in this SOW shall require a written change order signed by authorized representatives of both Parties. Consultant shall promptly notify Client if any circumstances arise that may require a change order. No work on a proposed change shall commence until the change order is fully executed.")
    pdf.section_heading("8", "ACCEPTANCE CRITERIA")
    pdf.body_text("Each deliverable shall be subject to Client's review and acceptance. Client shall have ten (10) business days to review each deliverable and provide written acceptance or rejection with specific reasons. Consultant shall address any deficiencies within five (5) business days. A deliverable shall be deemed accepted if Client does not provide written rejection within the review period.")
    pdf.signature_block([("Katherine A. Reynolds", "VP of Procurement", "Apple Inc."), ("David Kim", "Engagement Partner", "Pinnacle Consulting Group, Inc.")])
    pdf.output(os.path.join(OUTPUT_DIR, "SOW-DataMigration-Pinnacle-2023.pdf"))


def gen_vendor():
    pdf = ContractPDF("Vendor Agreement - GlobalTech / Pacific Logistics Corp.")
    pdf.alias_nb_pages()
    pdf.title_page("VENDOR AGREEMENT", ["GlobalTech Industries, Inc.", "and", "Pacific Logistics Corp."], "Effective Date: February 1, 2024", "Agreement No. GLB-PLC-VA-2024-0201")
    pdf.add_page()
    pdf.body_text('This Vendor Agreement ("Agreement") is entered into as of February 1, 2024 (the "Effective Date") by and between GlobalTech Industries, Inc., a Delaware corporation with its principal office at 2500 Corporate Boulevard, Chicago, IL 60601 ("Company"), and Pacific Logistics Corp., a Washington corporation with its principal office at 1800 Harbor Drive, Long Beach, CA 90802 ("Vendor"). Company and Vendor are collectively referred to as the "Parties."')
    pdf.section_heading("1", "SCOPE OF SERVICES")
    pdf.subsection_heading("1.1", "Services")
    pdf.body_text("Vendor shall provide the following warehousing and distribution services to Company: (a) receiving, inspection, and storage of Company's products and materials at Vendor's facilities; (b) inventory management, including real-time tracking, cycle counting, and reconciliation; (c) order fulfillment, including picking, packing, and shipping of products; (d) freight management and carrier coordination for domestic and international shipments; (e) returns processing and reverse logistics; and (f) value-added services including kitting, labeling, and light assembly as requested.")
    pdf.subsection_heading("1.2", "Facility")
    pdf.body_text("Vendor shall perform the services from its distribution center located at 1800 Harbor Drive, Long Beach, CA 90802, comprising approximately 250,000 square feet of climate-controlled warehouse space. Vendor shall maintain the facility in good condition, in compliance with all applicable building codes, health and safety regulations, and environmental requirements.")
    pdf.section_heading("2", "SERVICE LEVELS AND PERFORMANCE METRICS")
    pdf.subsection_heading("2.1", "Key Performance Indicators")
    pdf.body_text("Vendor shall meet or exceed the following key performance indicators (KPIs):\n  - Order Accuracy Rate: 99.5% or higher\n  - On-Time Shipment Rate: 98.0% or higher\n  - Inventory Accuracy: 99.7% or higher\n  - Receiving Turnaround: Within 24 hours of delivery\n  - Damage Rate: Less than 0.1% of units handled\n  - Customer Complaint Resolution: Within 48 hours")
    pdf.subsection_heading("2.2", "Performance Reviews")
    pdf.body_text("The Parties shall conduct quarterly business reviews to assess Vendor's performance against the KPIs. Vendor shall provide monthly performance reports no later than the tenth (10th) business day of each month. Persistent failure to meet KPIs over two consecutive quarters shall constitute a material breach of this Agreement.")
    pdf.section_heading("3", "FEES AND PAYMENT")
    pdf.subsection_heading("3.1", "Fee Schedule")
    pdf.body_text("Company shall pay Vendor in accordance with the following fee schedule:\n  - Storage Fee: $0.45 per pallet position per day\n  - Receiving Fee: $12.50 per pallet received\n  - Order Fulfillment Fee: $3.75 per order line picked and packed\n  - Shipping Handling Fee: $2.50 per parcel shipped\n  - Returns Processing: $8.00 per unit processed\n  - Kitting/Assembly: $15.00 per hour of labor\n\nEstimated annual spend based on current volumes: approximately $2,400,000 to $3,000,000 USD.")
    pdf.subsection_heading("3.2", "Invoicing and Payment Terms")
    pdf.body_text("Vendor shall submit itemized invoices on a monthly basis, no later than the fifth (5th) business day of the following month. Company shall pay all undisputed amounts within forty-five (45) days of receipt of a valid invoice. Company may withhold payment of any disputed amounts pending resolution, provided that Company notifies Vendor in writing within fifteen (15) days of receipt.")
    pdf.section_heading("4", "INSURANCE REQUIREMENTS")
    pdf.body_text("Vendor shall maintain at all times during the Term the following insurance coverage: (a) Commercial General Liability: $5,000,000 per occurrence, $10,000,000 aggregate; (b) Workers\' Compensation: as required by applicable law; (c) Automobile Liability: $2,000,000 combined single limit; (d) Warehouse Legal Liability: $10,000,000 per occurrence; (e) Umbrella/Excess Liability: $10,000,000 per occurrence. Vendor shall name Company as an additional insured on all policies and provide certificates of insurance within thirty (30) days of the Effective Date and upon each renewal.")
    pdf.section_heading("5", "TERM AND TERMINATION")
    pdf.subsection_heading("5.1", "Term")
    pdf.body_text('This Agreement shall commence on the Effective Date and continue for an initial term of five (5) years (the "Initial Term"), expiring on January 31, 2029. Thereafter, this Agreement shall automatically renew for successive two (2) year periods unless either Party provides written notice of non-renewal at least one hundred eighty (180) days prior to the expiration of the then-current term.')
    pdf.subsection_heading("5.2", "Termination for Cause")
    pdf.body_text("Either Party may terminate this Agreement upon written notice if the other Party: (a) materially breaches this Agreement and fails to cure such breach within forty-five (45) days after written notice; (b) becomes insolvent or files for bankruptcy protection; or (c) is convicted of fraud or any criminal offense related to the services.")
    pdf.subsection_heading("5.3", "Transition Assistance")
    pdf.body_text("Upon expiration or termination of this Agreement, Vendor shall provide transition assistance to Company or its designated successor for a period of up to ninety (90) days, at Vendor's then-current standard rates. During the transition period, Vendor shall continue to perform the services at the same service levels and cooperate fully with the transition.")
    pdf.section_heading("6", "LIABILITY AND INDEMNIFICATION")
    pdf.subsection_heading("6.1", "Cargo Liability")
    pdf.body_text("Vendor shall be liable for any loss, damage, or destruction of Company's products and materials while in Vendor's possession or control, except to the extent caused by Company's negligence, acts of God, or force majeure events. Vendor's maximum liability for cargo loss or damage shall be the lesser of: (a) the replacement value of the affected goods; or (b) $500,000 per occurrence.")
    pdf.subsection_heading("6.2", "Indemnification")
    pdf.body_text("Vendor shall indemnify, defend, and hold harmless Company from and against any and all claims, damages, losses, and expenses arising out of: (a) Vendor's negligence or willful misconduct; (b) Vendor's breach of this Agreement; (c) any injury to persons or damage to property occurring at Vendor's facility; or (d) Vendor's violation of applicable laws or regulations.")
    pdf.section_heading("7", "COMPLIANCE AND AUDIT RIGHTS")
    pdf.body_text("Vendor shall comply with all applicable federal, state, and local laws, regulations, and ordinances. Company shall have the right to audit Vendor's facilities, operations, records, and systems related to the services under this Agreement, upon reasonable notice and during normal business hours, no more than twice per calendar year. Vendor shall cooperate fully with any such audit.")
    pdf.section_heading("8", "GOVERNING LAW AND DISPUTE RESOLUTION")
    pdf.body_text("This Agreement shall be governed by and construed in accordance with the laws of the State of Illinois, without regard to its conflict of laws provisions. Any dispute arising under this Agreement shall first be submitted to good-faith mediation. If mediation is unsuccessful within sixty (60) days, either Party may initiate binding arbitration under the rules of the American Arbitration Association in Chicago, Illinois.")
    pdf.signature_block([("Michael D. Torres", "Chief Procurement Officer", "GlobalTech Industries, Inc."), ("Linda S. Nakamura", "President & CEO", "Pacific Logistics Corp.")])
    pdf.output(os.path.join(OUTPUT_DIR, "Vendor-Agreement-PacificLogistics-2024.pdf"))


if __name__ == "__main__":
    gen_nda()
    print("  [1/5] Mutual-NDA-TechCorp-Nexus-2024.pdf")
    gen_saas()
    print("  [2/5] SaaS-License-CloudVault-2024.pdf")
    gen_msa()
    print("  [3/5] MSA-Pinnacle-Consulting-2023.pdf")
    gen_sow()
    print("  [4/5] SOW-DataMigration-Pinnacle-2023.pdf")
    gen_vendor()
    print("  [5/5] Vendor-Agreement-PacificLogistics-2024.pdf")
    print("\nAll 5 contracts generated successfully.")
