#!/usr/bin/env python3
import os
from fpdf import FPDF

OUTPUT_DIR = "/Users/sreeja/Documents/GitHub/contract-intelligence/sample-contracts"
os.makedirs(OUTPUT_DIR, exist_ok=True)


class ContractPDF(FPDF):
    def __init__(self, title_text="", party_a="", party_b="", effective_date=""):
        super().__init__()
        self.title_text = title_text
        self.party_a = party_a
        self.party_b = party_b
        self.effective_date = effective_date
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            t = self.title_text.split(chr(10))[0]
            self.cell(0, 6, t, new_x="LMARGIN", new_y="NEXT", align="L")
            self.cell(0, 4, "Effective Date: " + self.effective_date, new_x="LMARGIN", new_y="NEXT", align="L")
            self.line(10, self.get_y()+1, 200, self.get_y()+1)
            self.ln(4)
            self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, "Page " + str(self.page_no()) + "/{nb}", align="C")
        self.set_text_color(0, 0, 0)

    def title_page(self):
        self.add_page()
        self.ln(50)
        self.set_font("Helvetica", "B", 22)
        self.multi_cell(0, 12, self.title_text, align="C")
        self.ln(12)
        self.set_font("Helvetica", "", 14)
        self.cell(0, 10, "by and between", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(4)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, self.party_a, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(2)
        self.set_font("Helvetica", "", 14)
        self.cell(0, 10, "and", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(2)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, self.party_b, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(16)
        self.set_font("Helvetica", "", 13)
        self.cell(0, 10, "Effective Date: " + self.effective_date, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(30)
        self.set_font("Helvetica", "I", 10)
        self.cell(0, 8, "CONFIDENTIAL", new_x="LMARGIN", new_y="NEXT", align="C")

    def section_heading(self, number, title):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, number + ". " + title, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def subsection_heading(self, number, title):
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 7, "    " + number + " " + title, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 5.5, text)
        self.ln(2)

    def signature_block(self, pa_name, pa_signer, pa_title, pb_name, pb_signer, pb_title):
        self.ln(8)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, "IN WITNESS WHEREOF", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 5.5, "The Parties hereto have executed this Agreement as of the date last signed below, intending to be legally bound hereby.")
        self.ln(10)
        y_start = self.get_y()
        self.set_font("Helvetica", "B", 10)
        self.cell(85, 6, pa_name, new_x="LMARGIN", new_y="NEXT")
        self.ln(12)
        self.line(10, self.get_y(), 90, self.get_y())
        self.ln(2)
        self.set_font("Helvetica", "", 9)
        self.cell(85, 5, "Signature", new_x="LMARGIN", new_y="NEXT")
        self.ln(6)
        self.set_font("Helvetica", "", 10)
        self.cell(85, 5, "Name: " + pa_signer, new_x="LMARGIN", new_y="NEXT")
        self.cell(85, 5, "Title: " + pa_title, new_x="LMARGIN", new_y="NEXT")
        self.cell(85, 5, "Date: _______________", new_x="LMARGIN", new_y="NEXT")
        y_after_a = self.get_y()
        self.set_y(y_start)
        self.set_x(110)
        self.set_font("Helvetica", "B", 10)
        self.cell(85, 6, pb_name)
        self.ln(12)
        self.line(110, self.get_y(), 195, self.get_y())
        self.set_y(self.get_y()+2)
        self.set_x(110)
        self.set_font("Helvetica", "", 9)
        self.cell(85, 5, "Signature")
        self.ln(6)
        self.set_x(110)
        self.set_font("Helvetica", "", 10)
        self.cell(85, 5, "Name: " + pb_signer)
        self.ln(5)
        self.set_x(110)
        self.cell(85, 5, "Title: " + pb_title)
        self.ln(5)
        self.set_x(110)
        self.cell(85, 5, "Date: _______________")
        self.set_y(max(y_after_a, self.get_y()) + 5)


def gen_nda():
    pdf = ContractPDF("Mutual Non-Disclosure Agreement", "TechCorp Solutions Inc.", "Nexus Dynamics LLC", "January 15, 2024")
    pdf.alias_nb_pages()
    pdf.title_page()
    pdf.add_page()
    pdf.body_text('This Mutual Non-Disclosure Agreement ("Agreement") is entered into as of January 15, 2024 (the "Effective Date"), by and between TechCorp Solutions Inc., a Delaware corporation with its principal offices at 2200 Innovation Drive, Suite 800, San Jose, CA 95134 ("TechCorp"), and Nexus Dynamics LLC, a California limited liability company with its principal offices at 450 Pacific Avenue, Suite 300, San Francisco, CA 94133 ("Nexus Dynamics"). TechCorp and Nexus Dynamics are each referred to herein individually as a "Party" and collectively as the "Parties."')
    pdf.section_heading("1", "PURPOSE")
    pdf.body_text('The Parties wish to explore a potential business relationship concerning the joint development and integration of advanced data analytics and artificial intelligence platforms (the "Purpose"). In connection with the Purpose, each Party may disclose to the other certain confidential and proprietary information. The Parties desire to provide for the protection and preservation of the confidentiality of such information in accordance with the terms of this Agreement.')
    pdf.section_heading("2", "DEFINITION OF CONFIDENTIAL INFORMATION")
    pdf.subsection_heading("2.1", "Scope.")
    pdf.body_text('"Confidential Information" means any and all non-public, proprietary, or confidential information disclosed by either Party (the "Disclosing Party") to the other Party (the "Receiving Party"), whether orally, in writing, electronically, or by inspection, including but not limited to: (a) trade secrets, inventions, patents, copyrights, trademarks, and other intellectual property; (b) business plans, strategies, forecasts, projections, and analyses; (c) financial information, pricing data, and customer lists; (d) technical data, know-how, research, product plans, software, source code, algorithms, designs, and specifications; (e) personnel information and organizational structures; and (f) any other information that a reasonable person would understand to be confidential given the nature of the information and the circumstances of disclosure.')
    pdf.subsection_heading("2.2", "Markings.")
    pdf.body_text('Written or electronic Confidential Information shall be marked as "Confidential," "Proprietary," or with a similar legend. Oral disclosures shall be identified as confidential at the time of disclosure and confirmed in writing within thirty (30) days thereafter.')
    pdf.section_heading("3", "EXCLUSIONS FROM CONFIDENTIAL INFORMATION")
    pdf.body_text("Confidential Information shall not include information that: (a) is or becomes publicly available through no fault of the Receiving Party; (b) was rightfully in the Receiving Party's possession prior to disclosure, as evidenced by written records; (c) is independently developed by the Receiving Party without use of or reference to the Disclosing Party's Confidential Information; (d) is rightfully obtained by the Receiving Party from a third party without restriction on disclosure and without breach of any obligation of confidentiality; or (e) is approved for release by written authorization of the Disclosing Party.")
    pdf.section_heading("4", "OBLIGATIONS OF THE RECEIVING PARTY")
    pdf.subsection_heading("4.1", "Non-Disclosure.")
    pdf.body_text('The Receiving Party shall: (a) hold the Confidential Information in strict confidence; (b) not disclose the Confidential Information to any third parties without the prior written consent of the Disclosing Party, except to its employees, officers, directors, advisors, and contractors ("Representatives") who have a need to know and who are bound by confidentiality obligations no less restrictive than those contained herein; and (c) use the Confidential Information solely for the Purpose.')
    pdf.subsection_heading("4.2", "Standard of Care.")
    pdf.body_text("The Receiving Party shall protect the Disclosing Party's Confidential Information using the same degree of care that it uses to protect its own confidential information of like nature, but in no event less than a reasonable degree of care.")
    pdf.section_heading("5", "COMPELLED DISCLOSURE")
    pdf.body_text("If the Receiving Party is compelled by law, regulation, or court order to disclose Confidential Information, the Receiving Party shall: (a) provide the Disclosing Party with prompt written notice of such requirement prior to disclosure (to the extent legally permitted); (b) cooperate with the Disclosing Party in seeking a protective order or other appropriate remedy; and (c) disclose only that portion of the Confidential Information which is legally required to be disclosed.")
    pdf.section_heading("6", "TERM AND TERMINATION")
    pdf.subsection_heading("6.1", "Term.")
    pdf.body_text("This Agreement shall commence on the Effective Date and shall remain in effect for a period of three (3) years, unless earlier terminated by either Party upon thirty (30) days' prior written notice to the other Party.")
    pdf.subsection_heading("6.2", "Survival.")
    pdf.body_text("The obligations of confidentiality set forth herein shall survive the termination or expiration of this Agreement for a period of three (3) years from the date of disclosure of the applicable Confidential Information.")
    pdf.section_heading("7", "RETURN OR DESTRUCTION OF MATERIALS")
    pdf.body_text("Upon termination of this Agreement or upon the written request of the Disclosing Party, the Receiving Party shall promptly return or destroy all copies of Confidential Information in its possession or control, and shall certify in writing to the Disclosing Party that it has complied with this obligation. Notwithstanding the foregoing, the Receiving Party may retain one (1) archival copy of such Confidential Information solely for legal compliance and record-keeping purposes, subject to the continuing confidentiality obligations herein.")
    pdf.section_heading("8", "NO LICENSE OR WARRANTY")
    pdf.body_text('Nothing in this Agreement grants the Receiving Party any license, by implication, estoppel, or otherwise, under any patent, copyright, trademark, or other intellectual property right of the Disclosing Party. ALL CONFIDENTIAL INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.')
    pdf.section_heading("9", "REMEDIES")
    pdf.body_text("Each Party acknowledges that any breach of this Agreement may cause irreparable harm to the Disclosing Party for which monetary damages would be an inadequate remedy. Accordingly, the Disclosing Party shall be entitled to seek equitable relief, including injunction and specific performance, in addition to all other remedies available at law or in equity, without the requirement of posting a bond or proving actual damages.")
    pdf.section_heading("10", "GENERAL PROVISIONS")
    pdf.subsection_heading("10.1", "Governing Law.")
    pdf.body_text("This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws principles.")
    pdf.subsection_heading("10.2", "Entire Agreement.")
    pdf.body_text("This Agreement constitutes the entire agreement between the Parties with respect to the subject matter hereof and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral.")
    pdf.subsection_heading("10.3", "Amendments.")
    pdf.body_text("No amendment or modification of this Agreement shall be valid or binding unless made in writing and signed by both Parties.")
    pdf.subsection_heading("10.4", "Notices.")
    pdf.body_text("All notices under this Agreement shall be in writing and shall be deemed given when delivered personally, sent by confirmed email, or sent by certified mail, return receipt requested, to the addresses set forth above or to such other address as a Party may designate in writing.")
    pdf.signature_block("TechCorp Solutions Inc.", "Margaret Chen", "Chief Executive Officer", "Nexus Dynamics LLC", "David Nakamura", "Managing Director")
    pdf.output(os.path.join(OUTPUT_DIR, "Mutual-NDA-TechCorp-Nexus-2024.pdf"))
    print("  [OK] Mutual-NDA-TechCorp-Nexus-2024.pdf")


def gen_saas():
    pdf = ContractPDF("Software-as-a-Service License Agreement", "GlobalTech Industries Inc.", "CloudVault Systems Inc.", "March 1, 2024")
    pdf.alias_nb_pages()
    pdf.title_page()
    pdf.add_page()
    pdf.body_text('This Software-as-a-Service License Agreement ("Agreement") is entered into as of March 1, 2024 (the "Effective Date"), by and between GlobalTech Industries Inc., a Delaware corporation with its principal offices at 500 Technology Parkway, Suite 1200, Austin, TX 78701 ("Customer"), and CloudVault Systems Inc., a Delaware corporation with its principal offices at 1800 Cloud Campus Drive, Suite 500, Seattle, WA 98101 ("Provider"). Customer and Provider are each referred to herein individually as a "Party" and collectively as the "Parties."')
    pdf.section_heading("1", "DEFINITIONS")
    pdf.body_text('"Service" means the CloudVault Enterprise Cloud Storage Platform, including all modules, features, updates, and enhancements made available by Provider during the Term. "Documentation" means Provider\'s standard user guides, online help, and technical manuals for the Service. "Authorized Users" means Customer\'s employees, contractors, and agents authorized by Customer to access the Service, not to exceed 2,500 user seats unless increased by written amendment. "Customer Data" means all electronic data, information, and content submitted by or on behalf of Customer to the Service. "SLA" means the Service Level Agreement attached hereto as Exhibit A.')
    pdf.section_heading("2", "GRANT OF LICENSE AND ACCESS")
    pdf.subsection_heading("2.1", "License Grant.")
    pdf.body_text("Subject to the terms and conditions of this Agreement, Provider hereby grants to Customer a non-exclusive, non-transferable, non-sublicensable right to access and use the Service during the Term solely for Customer's internal business operations.")
    pdf.subsection_heading("2.2", "Restrictions.")
    pdf.body_text("Customer shall not: (a) sublicense, sell, resell, transfer, assign, or distribute the Service; (b) modify or make derivative works based upon the Service; (c) reverse engineer, disassemble, or decompile the Service; (d) access the Service to build a competitive product or service; or (e) use the Service in violation of applicable laws or regulations.")
    pdf.section_heading("3", "FEES AND PAYMENT")
    pdf.subsection_heading("3.1", "Subscription Fees.")
    pdf.body_text('Customer shall pay Provider an annual subscription fee of Four Hundred Eighty Thousand Dollars ($480,000.00) per year (the "Subscription Fee"), payable in quarterly installments of One Hundred Twenty Thousand Dollars ($120,000.00) each, due on the first business day of each calendar quarter during the Term.')
    pdf.subsection_heading("3.2", "Price Escalation.")
    pdf.body_text("Subscription Fees for Renewal Terms (as defined below) shall be subject to an annual increase not to exceed four percent (4%) of the then-current Subscription Fee, provided that Provider gives Customer written notice at least ninety (90) days prior to the commencement of the applicable Renewal Term.")
    pdf.subsection_heading("3.3", "Late Payments.")
    pdf.body_text("Any amounts not paid when due shall bear interest at the lesser of one and one-half percent (1.5%) per month or the maximum rate permitted by applicable law. Customer shall reimburse Provider for all reasonable costs of collection, including attorneys' fees.")
    pdf.section_heading("4", "SERVICE LEVELS AND SUPPORT")
    pdf.subsection_heading("4.1", "Uptime Commitment.")
    pdf.body_text("Provider shall use commercially reasonable efforts to maintain Service availability of at least ninety-nine point nine percent (99.9%) measured on a monthly basis, excluding scheduled maintenance windows. Scheduled maintenance shall occur between 2:00 AM and 6:00 AM Pacific Time on Sundays, with at least 48 hours' advance notice to Customer.")
    pdf.subsection_heading("4.2", "Service Credits.")
    pdf.body_text("If Provider fails to meet the 99.9% uptime commitment in any calendar month, Customer shall be entitled to service credits as follows: (a) 99.0% - 99.8% availability: 10% credit of monthly fees; (b) 95.0% - 98.9% availability: 25% credit of monthly fees; (c) below 95.0% availability: 50% credit of monthly fees. Service credits shall be applied against future invoices and shall not exceed the total monthly fees for the affected period.")
    pdf.subsection_heading("4.3", "Support.")
    pdf.body_text("Provider shall provide 24/7 technical support via phone, email, and online portal. Critical severity issues (complete service outage) shall have a response time of fifteen (15) minutes. High severity issues shall have a response time of one (1) hour. Medium and low severity issues shall have a response time of four (4) business hours.")
    pdf.section_heading("5", "DATA PRIVACY AND SECURITY")
    pdf.subsection_heading("5.1", "Data Ownership.")
    pdf.body_text("Customer retains all right, title, and interest in and to Customer Data. Provider acquires no rights in Customer Data except as expressly set forth herein. Provider shall not access Customer Data except as necessary to provide the Service or as authorized by Customer.")
    pdf.subsection_heading("5.2", "Security Measures.")
    pdf.body_text("Provider shall maintain industry-standard administrative, physical, and technical safeguards to protect Customer Data, including: (a) AES-256 encryption at rest and TLS 1.3 encryption in transit; (b) SOC 2 Type II compliance, audited annually; (c) multi-factor authentication for all administrative access; (d) regular penetration testing by independent third parties; and (e) comprehensive logging and monitoring of all access to Customer Data.")
    pdf.subsection_heading("5.3", "Data Breach Notification.")
    pdf.body_text('In the event of any unauthorized access to or disclosure of Customer Data (a "Data Breach"), Provider shall notify Customer in writing within forty-eight (48) hours of discovering such Data Breach and shall cooperate fully with Customer in investigating and remediating the incident.')
    pdf.section_heading("6", "TERM AND TERMINATION")
    pdf.subsection_heading("6.1", "Initial Term.")
    pdf.body_text('This Agreement shall commence on the Effective Date and shall continue for an initial term of three (3) years (the "Initial Term").')
    pdf.subsection_heading("6.2", "Renewal.")
    pdf.body_text('Following the Initial Term, this Agreement shall automatically renew for successive one (1) year periods (each a "Renewal Term"), unless either Party provides written notice of non-renewal at least ninety (90) days prior to the end of the then-current term.')
    pdf.subsection_heading("6.3", "Termination for Cause.")
    pdf.body_text("Either Party may terminate this Agreement upon written notice if: (a) the other Party materially breaches this Agreement and fails to cure such breach within thirty (30) days after receiving written notice; or (b) the other Party becomes insolvent, files for bankruptcy, or ceases to operate in the ordinary course.")
    pdf.subsection_heading("6.4", "Effect of Termination.")
    pdf.body_text("Upon termination or expiration, Provider shall make Customer Data available for export in a standard format for a period of sixty (60) days, after which Provider shall securely delete all Customer Data from its systems and certify such deletion in writing.")
    pdf.section_heading("7", "LIMITATION OF LIABILITY")
    pdf.body_text("EXCEPT FOR BREACHES OF SECTION 5 (DATA PRIVACY AND SECURITY) OR A PARTY'S INDEMNIFICATION OBLIGATIONS, IN NO EVENT SHALL EITHER PARTY'S AGGREGATE LIABILITY UNDER THIS AGREEMENT EXCEED THE TOTAL FEES PAID OR PAYABLE BY CUSTOMER DURING THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM. IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.")
    pdf.section_heading("8", "GOVERNING LAW AND DISPUTE RESOLUTION")
    pdf.body_text("This Agreement shall be governed by the laws of the State of Delaware, without regard to its conflict of laws principles. Any dispute arising under this Agreement shall be resolved by binding arbitration administered by the American Arbitration Association in Wilmington, Delaware.")
    pdf.signature_block("GlobalTech Industries Inc.", "Robert Harrington", "Chief Procurement Officer", "CloudVault Systems Inc.", "Sarah Kim", "VP of Enterprise Sales")
    pdf.output(os.path.join(OUTPUT_DIR, "SaaS-License-CloudVault-2024.pdf"))
    print("  [OK] SaaS-License-CloudVault-2024.pdf")


def gen_msa():
    pdf = ContractPDF("Master Service Agreement", "Apple Inc.", "Pinnacle Consulting Group", "July 1, 2023")
    pdf.alias_nb_pages()
    pdf.title_page()
    pdf.add_page()
    pdf.body_text('This Master Service Agreement ("Agreement") is entered into as of July 1, 2023 (the "Effective Date"), by and between Apple Inc., a California corporation with its principal offices at One Apple Park Way, Cupertino, CA 95014 ("Client"), and Pinnacle Consulting Group, a New York limited liability company with its principal offices at 300 Park Avenue, Suite 1500, New York, NY 10022 ("Consultant"). Client and Consultant are each referred to herein individually as a "Party" and collectively as the "Parties."')
    pdf.section_heading("1", "SCOPE OF SERVICES")
    pdf.subsection_heading("1.1", "General.")
    pdf.body_text('Consultant shall provide information technology consulting services to Client as described in one or more Statements of Work (each, an "SOW") executed by both Parties and incorporated herein by reference. Each SOW shall specify the scope, deliverables, timeline, fees, and acceptance criteria for the applicable engagement.')
    pdf.subsection_heading("1.2", "Service Categories.")
    pdf.body_text("Services under this Agreement may include, but are not limited to: (a) IT strategy and digital transformation consulting; (b) cloud architecture design and migration services; (c) data engineering, analytics, and machine learning solutions; (d) cybersecurity assessment and remediation; (e) enterprise application development and integration; and (f) project management and program oversight.")
    pdf.section_heading("2", "FEES AND RATE CARDS")
    pdf.subsection_heading("2.1", "Rate Schedule.")
    pdf.body_text("Unless otherwise specified in an SOW, the following standard hourly rates shall apply:\n\n  Managing Director / Partner:     $450/hour\n  Senior Principal Consultant:     $375/hour\n  Principal Consultant:            $325/hour\n  Senior Consultant:               $275/hour\n  Consultant:                      $225/hour\n  Associate Consultant:            $175/hour\n  Analyst:                         $150/hour")
    pdf.subsection_heading("2.2", "Expenses.")
    pdf.body_text("Client shall reimburse Consultant for all reasonable, pre-approved travel and out-of-pocket expenses incurred in connection with the performance of Services, in accordance with Client's then-current travel and expense policy. Expenses exceeding Five Thousand Dollars ($5,000) in aggregate per month require prior written approval from Client.")
    pdf.subsection_heading("2.3", "Invoicing and Payment.")
    pdf.body_text("Consultant shall submit itemized invoices on a monthly basis. All invoices shall be payable within thirty (30) days of receipt. Disputed amounts must be communicated in writing within fifteen (15) business days of invoice receipt; undisputed amounts shall be paid in full when due.")
    pdf.section_heading("3", "INTELLECTUAL PROPERTY")
    pdf.subsection_heading("3.1", "Work Product Ownership.")
    pdf.body_text('All work product, deliverables, inventions, discoveries, designs, code, documentation, and other materials created by Consultant specifically for Client in connection with this Agreement (collectively, "Work Product") shall be the sole and exclusive property of Client. Consultant hereby assigns to Client all right, title, and interest in and to the Work Product, including all intellectual property rights therein.')
    pdf.subsection_heading("3.2", "Pre-Existing Materials.")
    pdf.body_text('Consultant retains all right, title, and interest in and to any pre-existing materials, tools, methodologies, frameworks, and know-how owned or licensed by Consultant prior to the Effective Date or developed independently outside the scope of this Agreement ("Consultant Materials"). To the extent any Consultant Materials are incorporated into Work Product, Consultant hereby grants Client a non-exclusive, perpetual, irrevocable, royalty-free, worldwide license to use such Consultant Materials solely as part of and in connection with the Work Product.')
    pdf.section_heading("4", "CONFIDENTIALITY")
    pdf.body_text("Each Party shall hold in confidence all Confidential Information of the other Party and shall not disclose such information to any third party without the prior written consent of the Disclosing Party. This obligation shall survive the termination or expiration of this Agreement for a period of five (5) years. Consultant acknowledges that, in the course of performing Services, it may have access to Client's trade secrets, product roadmaps, and proprietary technologies, and agrees to safeguard such information with the utmost care.")
    pdf.section_heading("5", "NON-SOLICITATION")
    pdf.body_text("During the Term and for a period of twelve (12) months following its expiration or termination, neither Party shall, directly or indirectly, solicit, recruit, or hire any employee or contractor of the other Party who was involved in the performance of Services under this Agreement, without the prior written consent of the other Party. This restriction shall not apply to general employment advertisements not specifically targeted at such individuals.")
    pdf.section_heading("6", "REPRESENTATIONS AND WARRANTIES")
    pdf.subsection_heading("6.1", "Consultant Warranties.")
    pdf.body_text("Consultant represents and warrants that: (a) it has the authority and capacity to enter into this Agreement; (b) Services will be performed in a professional and workmanlike manner by qualified personnel; (c) Work Product will not infringe upon the intellectual property rights of any third party; and (d) it is in compliance with all applicable laws, regulations, and industry standards.")
    pdf.subsection_heading("6.2", "Client Warranties.")
    pdf.body_text("Client represents and warrants that: (a) it has the authority to enter into this Agreement; and (b) it shall provide reasonable access to information, systems, and personnel necessary for Consultant to perform the Services.")
    pdf.section_heading("7", "INDEMNIFICATION")
    pdf.body_text('Each Party (the "Indemnifying Party") shall indemnify, defend, and hold harmless the other Party and its officers, directors, employees, and agents (the "Indemnified Parties") from and against any third-party claims, damages, losses, costs, and expenses (including reasonable attorneys\' fees) arising from: (a) the Indemnifying Party\'s breach of this Agreement; (b) the Indemnifying Party\'s negligence or willful misconduct; or (c) any violation of applicable law by the Indemnifying Party.')
    pdf.section_heading("8", "TERM AND TERMINATION")
    pdf.subsection_heading("8.1", "Term.")
    pdf.body_text('This Agreement shall commence on the Effective Date and shall continue for an initial term of two (2) years (the "Initial Term"). Following the Initial Term, this Agreement shall automatically renew for successive one (1) year periods (each a "Renewal Term"), unless either Party provides written notice of non-renewal at least sixty (60) days prior to the end of the then-current term.')
    pdf.subsection_heading("8.2", "Termination for Convenience.")
    pdf.body_text("Either Party may terminate this Agreement or any SOW for convenience upon sixty (60) days' prior written notice. In the event of termination for convenience, Client shall pay Consultant for all Services satisfactorily performed and expenses properly incurred through the effective date of termination.")
    pdf.subsection_heading("8.3", "Termination for Cause.")
    pdf.body_text("Either Party may terminate this Agreement upon written notice if the other Party materially breaches this Agreement and fails to cure such breach within thirty (30) days after receiving written notice specifying the nature of the breach.")
    pdf.section_heading("9", "LIMITATION OF LIABILITY")
    pdf.body_text("EXCEPT FOR BREACHES OF CONFIDENTIALITY, INTELLECTUAL PROPERTY INFRINGEMENT, OR INDEMNIFICATION OBLIGATIONS, NEITHER PARTY'S AGGREGATE LIABILITY UNDER THIS AGREEMENT SHALL EXCEED THE TOTAL FEES PAID OR PAYABLE UNDER THE APPLICABLE SOW GIVING RISE TO THE CLAIM. NEITHER PARTY SHALL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.")
    pdf.section_heading("10", "GOVERNING LAW AND DISPUTE RESOLUTION")
    pdf.body_text("This Agreement shall be governed by the laws of the State of California. Any dispute arising under this Agreement shall first be submitted to good faith mediation. If mediation is unsuccessful within sixty (60) days, the dispute shall be resolved by binding arbitration administered by JAMS in San Francisco, California.")
    pdf.section_heading("11", "GENERAL PROVISIONS")
    pdf.body_text("This Agreement, together with all SOWs and exhibits, constitutes the entire agreement between the Parties. No amendment shall be effective unless in writing and signed by both Parties. Neither Party may assign this Agreement without the other Party's prior written consent, except in connection with a merger, acquisition, or sale of substantially all of its assets. If any provision of this Agreement is held to be unenforceable, the remaining provisions shall continue in full force and effect.")
    pdf.signature_block("Apple Inc.", "Jennifer Walsh", "VP of Strategic Procurement", "Pinnacle Consulting Group", "Michael Torres", "Managing Partner")
    pdf.output(os.path.join(OUTPUT_DIR, "MSA-Pinnacle-Consulting-2023.pdf"))
    print("  [OK] MSA-Pinnacle-Consulting-2023.pdf")


def gen_sow():
    pdf = ContractPDF("Statement of Work #001\nData Migration & Cloud Infrastructure", "Apple Inc.", "Pinnacle Consulting Group", "August 15, 2023")
    pdf.alias_nb_pages()
    pdf.title_page()
    pdf.add_page()
    pdf.body_text('This Statement of Work #001 ("SOW") is entered into as of August 15, 2023, pursuant to and governed by the Master Service Agreement dated July 1, 2023 (the "MSA"), by and between Apple Inc. ("Client") and Pinnacle Consulting Group ("Consultant"). In the event of any conflict between this SOW and the MSA, the terms of this SOW shall prevail with respect to the subject matter hereof. Capitalized terms used herein and not otherwise defined shall have the meanings ascribed to them in the MSA.')
    pdf.section_heading("1", "PROJECT OVERVIEW")
    pdf.body_text("Consultant shall provide data migration and cloud infrastructure services to transition Client's legacy on-premises data center infrastructure to Amazon Web Services (AWS) and Microsoft Azure cloud platforms. The project encompasses the migration of approximately 85 terabytes of structured and unstructured data, 120+ application workloads, and the establishment of a hybrid cloud architecture with high availability and disaster recovery capabilities.")
    pdf.section_heading("2", "SCOPE OF SERVICES")
    pdf.subsection_heading("2.1", "Phase 1: Discovery and Assessment (Weeks 1-4)")
    pdf.body_text("Consultant shall: (a) conduct a comprehensive inventory of all existing infrastructure, applications, and data assets; (b) assess application dependencies, performance baselines, and compatibility with target cloud platforms; (c) identify migration risks and develop risk mitigation strategies; (d) produce a detailed Migration Plan and Architecture Design Document for Client review and approval.")
    pdf.subsection_heading("2.2", "Phase 2: Infrastructure Setup (Weeks 5-10)")
    pdf.body_text("Consultant shall: (a) provision and configure AWS and Azure environments in accordance with the approved Architecture Design; (b) implement network connectivity including VPN tunnels, Direct Connect, and ExpressRoute circuits; (c) establish identity and access management (IAM) frameworks; (d) deploy monitoring, logging, and alerting infrastructure using CloudWatch, Azure Monitor, and Datadog; (e) implement security controls including encryption, firewall rules, and compliance scanning.")
    pdf.subsection_heading("2.3", "Phase 3: Data Migration (Weeks 11-18)")
    pdf.body_text("Consultant shall: (a) execute the data migration in accordance with the approved Migration Plan, utilizing AWS Database Migration Service, Azure Data Factory, and custom ETL pipelines; (b) perform data validation and integrity checks at each stage; (c) migrate databases including Oracle, PostgreSQL, and MongoDB instances; (d) transfer unstructured data including file shares, object storage, and archival data.")
    pdf.subsection_heading("2.4", "Phase 4: Application Migration (Weeks 15-22)")
    pdf.body_text("Consultant shall: (a) migrate application workloads using a combination of lift-and-shift, re-platforming, and re-architecting strategies as identified in the Migration Plan; (b) containerize selected applications using Docker and deploy on Amazon EKS and Azure AKS; (c) reconfigure application settings, connection strings, and integrations for the cloud environment; (d) conduct performance testing and optimization.")
    pdf.subsection_heading("2.5", "Phase 5: Validation and Cutover (Weeks 23-26)")
    pdf.body_text("Consultant shall: (a) conduct comprehensive end-to-end testing in the cloud environment; (b) execute a phased cutover plan with defined rollback procedures; (c) perform parallel operations for critical systems during a two-week stabilization period; (d) decommission legacy infrastructure upon Client's written approval; (e) conduct knowledge transfer sessions for Client's IT team.")
    pdf.section_heading("3", "DELIVERABLES")
    pdf.body_text("Consultant shall deliver the following:\n\n  D1. Infrastructure Assessment Report\n  D2. Migration Plan and Architecture Design Document\n  D3. Risk Register and Mitigation Plan\n  D4. Provisioned and Configured Cloud Environments\n  D5. Migrated Databases and Data Stores (validated)\n  D6. Migrated Application Workloads (tested)\n  D7. Disaster Recovery and Business Continuity Plan\n  D8. Security and Compliance Audit Report\n  D9. Operations Runbook and Documentation\n  D10. Knowledge Transfer Materials and Training Sessions")
    pdf.section_heading("4", "ACCEPTANCE CRITERIA")
    pdf.body_text("Each Deliverable shall be subject to Client's acceptance review. Client shall have ten (10) business days following delivery to review and either accept the Deliverable or provide a detailed written notice of rejection specifying the deficiencies. Consultant shall have ten (10) business days to cure any deficiencies and resubmit. A Deliverable shall be deemed accepted if Client fails to provide notice within the review period. Final project acceptance requires: (a) all Deliverables accepted; (b) 99.5% data integrity validation; (c) application performance within 10% of baseline measurements; and (d) successful completion of disaster recovery testing.")
    pdf.section_heading("5", "PROJECT TIMELINE AND MILESTONES")
    pdf.body_text("  Milestone 1 - Project Kickoff:               August 15, 2023\n  Milestone 2 - Assessment Complete:            September 12, 2023\n  Milestone 3 - Infrastructure Ready:           October 24, 2023\n  Milestone 4 - Data Migration Complete:        December 19, 2023\n  Milestone 5 - Application Migration Complete: January 16, 2024\n  Milestone 6 - Final Cutover and Acceptance:   February 13, 2024")
    pdf.section_heading("6", "FEES AND PAYMENT SCHEDULE")
    pdf.subsection_heading("6.1", "Total Project Fee.")
    pdf.body_text('The total fixed price for all Services and Deliverables under this SOW is One Million Two Hundred Thousand Dollars ($1,200,000.00) (the "Project Fee").')
    pdf.subsection_heading("6.2", "Payment Milestones.")
    pdf.body_text("The Project Fee shall be payable in accordance with the following milestone-based schedule:\n\n  Payment 1 - Upon SOW Execution:          $180,000 (15%)\n  Payment 2 - Assessment Complete (M2):     $120,000 (10%)\n  Payment 3 - Infrastructure Ready (M3):    $240,000 (20%)\n  Payment 4 - Data Migration Complete (M4): $300,000 (25%)\n  Payment 5 - App Migration Complete (M5):  $240,000 (20%)\n  Payment 6 - Final Acceptance (M6):        $120,000 (10%)")
    pdf.subsection_heading("6.3", "Change Orders.")
    pdf.body_text("Any changes to the scope, schedule, or fees set forth in this SOW shall require a written change order signed by authorized representatives of both Parties. Consultant shall not perform out-of-scope work without an approved change order.")
    pdf.section_heading("7", "PROJECT TEAM AND GOVERNANCE")
    pdf.subsection_heading("7.1", "Consultant Team.")
    pdf.body_text("Consultant shall assign the following key personnel to this project:\n\n  Project Director: James Liu (Managing Director)\n  Lead Cloud Architect: Priya Sharma (Senior Principal Consultant)\n  Data Migration Lead: Carlos Rodriguez (Principal Consultant)\n  Security Lead: Anna Kowalski (Senior Consultant)\n  Plus 8-12 additional engineers and analysts as needed")
    pdf.subsection_heading("7.2", "Governance.")
    pdf.body_text("The project shall follow an Agile methodology with two-week sprints. Status meetings shall be held weekly, and executive steering committee meetings shall be held monthly. Consultant shall provide written progress reports bi-weekly, including milestone tracking, risk updates, and budget status.")
    pdf.section_heading("8", "ASSUMPTIONS AND DEPENDENCIES")
    pdf.body_text("This SOW is based on the following assumptions: (a) Client shall provide timely access to all required systems, environments, and personnel; (b) Client's existing infrastructure is substantially as described during pre-engagement discussions; (c) network bandwidth between on-premises and cloud environments shall be at least 10 Gbps; (d) Client shall designate a Project Manager with authority to make day-to-day decisions; (e) third-party vendor cooperation will be available as needed. Material deviations from these assumptions may result in change orders.")
    pdf.signature_block("Apple Inc.", "Jennifer Walsh", "VP of Strategic Procurement", "Pinnacle Consulting Group", "Michael Torres", "Managing Partner")
    pdf.output(os.path.join(OUTPUT_DIR, "SOW-DataMigration-Pinnacle-2023.pdf"))
    print("  [OK] SOW-DataMigration-Pinnacle-2023.pdf")
